### ISSUE TITLE
dipendenze

### ISSUE THREAD

**Issue by lplume** [emergenzeHack/ems_toolkit#2]
Buondì, 

vedo che la repo è fresca fresca, ti segnalo le dipendenze per runnare il progetto pyshp, requests, html5lib, beautifoulsoup4.

Cordialmente

**Comment by iltempe** [comment]
ciao @lplume si hai ragione. Direi di mettere tutte le dipendenze nel readme file in modo tale che si sappia cosa installare. Grazie mille!. Repo freschissima cmq vedi anche #1 se vuoi.

**Comment by lplume** [comment]
se non mi batti sul tempo :p stavo giusto provando a runnare il tutto (giusto runnare) se puoi editare e spiegare meglio cosa non succede e cosa ci si aspetta mi faresti un grosso favorone... Di prima mi sembra di aver notato che i vari folder di in-out ad un certo punto non coincidono, personalmente lo semplificherei un pochino e renderei parametrizzabili certi parametri (direttamente da cli); purtroppo non ho sensibilità sul progetto di per se, quindi non saprei se, per esempio, sia necessario salvare gli intermedi file shp non mergiati (per intenderci quelli che escono dagli zip). Ripeto, questi sono i miei 50cent, se riesci a darmi queste info potrei rivedere un po' come e perché, sfortunatamente sono un po' imballato coi tempi, ma se posso aiutare collaboro volentieri, in primis perché mi piace farlo e secondariamente seguo da un po' i tuoi lavori e mi piacciono molto, per cui, compatibilmente con gli impegni sono a bordo =) !

buona serata

**Comment by iltempe** [comment]
ok grazie! beh io qui accetto pul request. la prima cosa da fare sarebbe sistemare l' #1 . lo script di merge secondo me va abbastanza bene...anche se possiamo aprire issue più specifici per migliorarlo. Per il tempo, nessun problema anche io ci lavoro quando posso! grazie!

**Comment by jenkin** [comment]
Le dipendenze vanno scritte nel [file requirements.txt](https://pip.readthedocs.io/en/1.1/requirements.html) e installate con pip: `pip install -r requirements.py`. Meglio se all'interno di un [virtualenv](https://virtualenv.pypa.io/en/stable/) (che personalmente uso mediante questo comodo [wrapper](https://virtualenvwrapper.readthedocs.io/en/latest/)).
